var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                  yyy           ",
   "                                                   yy      yy    yyyyy          ",
   "                                    o o      yy                  y!y!y          ",
   "                                                                 yyyyy          ",
   "                                   yyyyy                          y!y           ",
   "                                                                  yvy       xx  ",
   "  xx                                      o o                                x  ",
   "  xp                    o                                                    x  ",
   "  x             $                         xxxxx                             o x  ",
   "  x          yyyy       o       $                          $     $$$$        x  ",
   "  x  @   $   y!!y                    ooooo         yy            yyyyy       x  ",
   "  xxxxxxxxxxxx!!xxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxx     xxxxxxx   xxxxxxxxx  ",
   "              !!              y   y                  y     y                    ",
   "              !!              y!!!y                  y!!!!!y                    ",
   "              !!              y!!!y                  y!!!!!y                    ",
   "              !!              yyyyy                  yyyyyyy                    ",
   "              !!                                                                ",
   "              !!                                                                "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "  y      y      y      y      y      y    y  y   y                                                            ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "  |      |      |      |      |      |    |  |   |                                                            ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                    o                                                                                         ",
   "                    x      o                                                                                  ",
   "             o      x      x      o                                                                           ",
   "     @       x      x      x      x                                                                           ",
   "    xxx      x      x      x      x    o                                                                      ",
   "    x x  p   x      x      x      x    x   o                                                                  ",
   "!!!!x x!!!!!!x!!!!!!x!!!!!!x!!!!!!x!!!!x!!!x       $                                                          ",
   "!!!!x x!!!!!!x!!!!!!x!!!!!!x!!!!!!x!!!!x!!!x  o                                                               ",
   "!!!!x x!!!!!!x!!!!!!x!!!!!!x!!!!!!x!!!!x!!!x  x    o                                                          ",
   "!!!!x x!!!!!!x!!!!!!x!!!!!!x!!!!!!x!!!!x!!!x  x    x            y   y    y                                    ",
   "!!!!x x!!!!!!x!!!!!!x!!!!!!x!!!!!!x!!!!x!!!x  x    x                                                          ",
   "!!!!x x!!!!!!x!!!!!!x!!!!!!x!!!!!!x!!!!x!!!x  x    x  ooooooooooo$$$$$$$o$$$oo =x                             ",
   "!!!!x x!!!!!!x!!!!!!x!!!!!!x!!!!!!x!!!!x!!!x  x!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxx                                "],
  ["  x                                                                                                           ",
   "  x       @      |                                                                                             ",
   "  x                                 |               |                                                         ",
   "  x                                                       y   =    y                                          ",
   "  x                                                                                                           ",
   "  x =                                                                                                         ",
   "  x                         |                                                                                 ",
   "  x                                                     |           y  =   y                                  ",
   "  x =           |                                                                                             ",
   "  x                                          |                                                                ",
   "  x                                                                                                           ",
   "  x                     y =         y                      |                                                  ",
   "  x                                    |                                                                      ",
   "  x                                                                                                           ",
   "  x                                                                                                           ",
   "  x   |                          |                                                                            ",
   "  x                                           y   =  y                                                        ",
   "  x                     |                                                                                     ",
   "  x                                                              |                                            ",
   "  x |                                                                                                         ",
   "  x                                                                                                           ",
   "  x                                                                                                           ",
   "  x   =    y                  |                                                                               ",
   "  x                                                                                                           ",
   "  x                                                            =                                              ",
   "  x                                                                                                           ",
   "  x                                                                                                           ",
   "  x                                                                                                           ",
   "  x                |                       |                                                                  ",
   "  x                                                y   =                                                      ",
   "  x   =   y                                                                                                   ",
   "  x                                                                                                           ",
   "  x                                                                                                           ",
   "  x                                                                                                           ",
   "  x                                                                                                           ",
   "  x                                                                                                           ",
   "  x                         =y         |                                                                      ",
   "  x  |                                                                                                        ",
   "  x                |                                      = y                                                 ",
   "  x                                                                                                           ",
   "  x                                                                                                           ",
   "  x    =        y                           y y y y y                                                         ",
   "  x                                |         y     y                    = y                                   ",
   "  x =                                            o             =                                  =y          ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxpxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx            ",
   "       x                                                                                                      ",
   "       x                                                                                                      "],


  ["       x                                                                                                      ",
   "       x                                                                                                      ",
   "       x                                                                                                      ",
   "       x                                                                                                      ",
   "       x                                                                                                      ",
   "       x                                                                                                      ",
   "       x                                                                                                      ",
   "       x   yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy                                           ",
   "       x   y                                                      y                                           ",
   "       x   y xxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!y                                           ",
   "       x   y x p xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx y                                           ",
   "       x   y x       x         x         x        x             ! y                                           ",
   "       xxxxxxx   o    x    o    x    o    x    o        o    o  ! y                                           ",
   "       !         x    x    x    x    x    x   x         x    x  ! y                                           ",
   "       !         x         x         x        x    x    x    x  ! y                                           ",
   "       !  @  $   x o     o x o       x o     oxo   x  o x o  x  ! y                                          ",
   "       !xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx! y                                          ",
   "      y!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!y                                           ",
   "       yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy                                           ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   " xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ",
   "                                                                                                              "],
   ["                                                                                                                      ",
   "																											                                                                        ",
   "																										                                                                     ",
   "																											                                                                       ",
   "                                                                                                                      ",
   "																										                                                                     	  ",
   "																											                                                                           ",
   "                 																					                                                              		  ",
   "                xx  xx   xxxxxx   xx    xx         xx           xx   xx  xxxx     xx   xx                             ",
   "                xx  xx   xx  xx   xx    xx         xx           xx       xx  x    xx   xx                                           ",
   "                xxxxxx   xx  xx   xx    xx         xx    xxx    xx   xx  xx   x   xx   xx                                  ",
   "                  xx     xx  xx   xx    xx         xx   x   x   xx   xx  xx    x  xx   xx                                                  ",
   "                  xx     xx  xx   xx    xx         xx  x     x  xx   xx  xx     x xx                                   ",
   "                  xx     xxxxxx   xxxxxxxx         xxxx       xxxx   xx  xx      xxx   xx                                                      ",
   "                                                                                                                                ",
   "                               																			                                                          	  ",
   "																										                                                                              	  ",
   "																											                                                                             ",
   "																									@		                                                                            ",
   "					                                      					                                                                        ",
   " 																											                                                                                     ",
   "				                                     					                                                                                 ",
   "					                                                                                                                       				  ",
   "					o	o	o	o	o	o	o	o	o	o	o	o	o	o	o	o	o	o$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ooooooooooooooooooooooooooooooooop					                                                            ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"]

];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
